name: Hello World Action

on:
  push:
    branches:
      - main  # 这里可以修改为你需要触发的分支

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run: echo "Hello, World!"
